  - name: add influxdb repository
    yum_repository:
        name: influxdb
        description: InfluxDB Repository - RHEL \$releasever
        baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
        gpgcheck: yes
        gpgkey: https://repos.influxdata.com/influxdb.key
        enabled: yes

  - name: installing dependencies
    yum: name={{ item }} state=present
    with_items:
      - influxdb

  - name: start influxdb service
    service: name=influxdb state=started enabled=yes

  - name: Create sample database
    command: /opt/influxdb/influx -execute 'CREATE DATABASE sensors_db'
