  - name: install grafana rpm file
    dnf: name=https://grafanarel.s3.amazonaws.com/builds/grafana-3.1.1-1470047149.x86_64.rpm state=present

  - name: start grafana service
    service: name=grafana-server state=started enabled=yes
