  - name: install node-red
    command: npm install -g --unsafe-perm node-red

  - name: create flow from template
    template: src=flows_server0.json.j2 dest=/home/vagrant/.node-red owner=vagrant group=vagrant mode=0664

  - name: start node-red service
    systemd: name=nodered state=started enabled=yes
