  - name: install epel-release
    yum: name=epel-release state=present
    when: ansible_distribution in ['RedHat', 'CentOS']

  - name: installing dependencies
    package: name={{ item }} state=present
    with_items:
      - gcc-c++
      - make
      - nodejs
      - npm
      - python-pip
      - wget
      - go
      - git

  - name: installing pip-dependencies
    pip: name={{ item }} state=present extra_args='--upgrade'
    with_items:
      - influxdb
